name = "image2vrc"
pages_build_output_dir = "public"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm ci"

[observability]
enabled = true

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "image2vrc"
